version: "3.1"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: pz
      POSTGRES_USER: pz
      POSTGRES_PASSWORD: pz
    ports:
      - "5431:5432"
    volumes:
      - pz-db:/var/lib/postgresql/data
#    networks:
#      - pz

  mongo:
    image: mongo:4.2.16
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-db:/data/db

  redis:
    image: bitnami/redis:6.2.12
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis-init:/bitnami/redis/data/

volumes:
  pz-db:
  mongo-db:
  redis-init:

#networks:
#  pz:
#    driver: bridge