# FILE LOCATION
FILEPATH = '../data/data_test_3.csv'

# DATABASE CONNECTION
HOST = "localhost"
POSTGRES_PORT = "5431"
MONGO_PORT = "27017"
REDIS_PORT = "6379"
PASSWORD = "admin"
USER = "admin"
DATABASE_NAME = "ztbd"


# DATABASE TYPE
POSTGRESQL = "PostgreSQL"
MONGODB = "MongoDB"
REDIS = "Redis"
